// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package domain

import (
	"time"
)

const TableNameArticle = "article"

// Article mapped from table <article>
type Article struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:文章ID，主键，自增长" json:"id"`          // 文章ID，主键，自增长
	Title        string    `gorm:"column:title;not null;comment:文章标题" json:"title"`                                // 文章标题
	Content      string    `gorm:"column:content;not null;comment:文章正文内容（支持Markdown或HTML格式）" json:"content"`       // 文章正文内容（支持Markdown或HTML格式）
	Summary      string    `gorm:"column:summary;comment:文章摘要/简要描述（可用于列表页或SEO）" json:"summary"`                    // 文章摘要/简要描述（可用于列表页或SEO）
	CoverImage   string    `gorm:"column:cover_image;comment:文章封面图片URL" json:"cover_image"`                        // 文章封面图片URL
	CategoryID   int64     `gorm:"column:category_id;comment:分类ID，关联category表" json:"category_id"`                 // 分类ID，关联category表
	Tags         string    `gorm:"column:tags;default:{};comment:标签，数组格式" json:"tags"`                             // 标签，数组格式
	AuthorID     int64     `gorm:"column:author_id;not null;comment:作者ID，关联user表" json:"author_id"`                // 作者ID，关联user表
	ViewCount    int32     `gorm:"column:view_count;comment:文章阅读次数" json:"view_count"`                             // 文章阅读次数
	CommentCount int32     `gorm:"column:comment_count;comment:文章评论数" json:"comment_count"`                        // 文章评论数
	IsPublished  bool      `gorm:"column:is_published;comment:是否发布：false=未发布（草稿），true=已发布" json:"is_published"`    // 是否发布：false=未发布（草稿），true=已发布
	CreatedAt    time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP;comment:文章创建时间" json:"created_at"`   // 文章创建时间
	UpdatedAt    time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP;comment:文章最后更新时间" json:"updated_at"` // 文章最后更新时间
}

// TableName Article's table name
func (*Article) TableName() string {
	return TableNameArticle
}
