// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package domain

import (
	"time"
)

const TableNameComment = "comment"

// Comment mapped from table <comment>
type Comment struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:评论ID，自增长主键" json:"id"`                  // 评论ID，自增长主键
	ArticleID   int64     `gorm:"column:article_id;not null;comment:关联文章ID" json:"article_id"`                           // 关联文章ID
	ParentID    int64     `gorm:"column:parent_id;comment:父评论ID，支持评论回复，NULL表示顶级评论" json:"parent_id"`                     // 父评论ID，支持评论回复，NULL表示顶级评论
	AuthorID    int64     `gorm:"column:author_id;not null;comment:评论作者ID" json:"author_id"`                             // 评论作者ID
	Content     string    `gorm:"column:content;not null;comment:评论内容" json:"content"`                                   // 评论内容
	IsPublished bool      `gorm:"column:is_published;not null;default:true;comment:评论是否展示，默认展示" json:"is_published"`     // 评论是否展示，默认展示
	LikeCount   int32     `gorm:"column:like_count;not null;comment:点赞数，默认0" json:"like_count"`                          // 点赞数，默认0
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:评论创建时间" json:"created_at"` // 评论创建时间
	UpdatedAt   time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:评论更新时间" json:"updated_at"` // 评论更新时间
}

// TableName Comment's table name
func (*Comment) TableName() string {
	return TableNameComment
}
